_wandb:
    value:
        cli_version: 0.19.9
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 9
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 103
            "2":
                - 1
                - 2
                - 3
                - 5
                - 9
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 103
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.10.12
            "5": 0.19.9
            "6": 4.51.1
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
