# pytorch_lightning==2.5.5
seed_everything: 0
trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: bema 
      entity: pyle-lab
      settings:
        code_dir: ./lit_lm
  accelerator: gpu
  strategy: auto
  devices: -1
  num_nodes: 1
  precision: bf16-mixed
  callbacks: null
  max_epochs: 1
  max_steps: -1
  val_check_interval: 100
  log_every_n_steps: 10
  accumulate_grad_batches: 2
  gradient_clip_val: 1.0
model:
  pretrained_model_name_or_path: gpt2
data:
  batch_size: 8
  dataset_name: wikitext
  dataset_config: wikitext-2-raw-v1
  pretrained_model_name_or_path: gpt2
  text_key: text
  max_length: 512
  num_workers: 4
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 3.0e-05
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    weight_decay: 0.01
    amsgrad: false
    maximize: false
    foreach: null
    capturable: false
    differentiable: false
    fused: null
lr_scheduler: null
ckpt_path: null
