# pytorch_lightning==2.5.5
seed_everything: 0
trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: BEMA 
      settings:
        code_dir: ./lit_lm
  limit_val_batches: 200
  val_check_interval: 200
  precision: bf16-mixed
  callbacks:
    - class_path: lit_lm.callbacks.BEMACallback
      init_args:
        ema_power: 0.999
        bias_power: null
        frequency: 10
  max_epochs: 1
  accumulate_grad_batches: 1
model:
  pretrained_model_name_or_path: gpt2
data:
  batch_size: 1
  dataset_name: wikitext
  dataset_config: wikitext-2-raw-v1
  pretrained_model_name_or_path: ${model.pretrained_model_name_or_path}
  text_key: text
  max_length: 512
  num_workers: 4
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1.0e-03
    weight_decay: 0.01
lr_scheduler: null
ckpt_path: null
